name: build

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux-x64, linux-arm64, windows-x64, windows-arm64, macos-arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: build
        run: ./gradlew build

      - name: release binary
        run: ./gradlew $(cat ${{ matrix.target }} | tr '-arm64' 'Arm64' | tr '-x64' 'X64')Binary

      - name: archive vat
        uses: actions/upload-artifact@v4
        with:
          name: vat
          path: build/libs/vat-${{ matrix.target }}
